services:
  - type: web
    name: guinyote-server
    env: node
    buildCommand: cd Servidor && npm install
    startCommand: cd Servidor && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000 